export const GOOGLE_FONTS = [
    { name: 'Inter', category: 'sans-serif' },
    { name: 'Outfit', category: 'sans-serif' },
    { name: 'Space Grotesk', category: 'sans-serif' },
    { name: 'Syne', category: 'display' },
    { name: 'Manrope', category: 'sans-serif' },
    { name: 'Plus Jakarta Sans', category: 'sans-serif' },
    { name: 'Unbounded', category: 'display' },
    { name: 'Sora', category: 'sans-serif' },
    { name: 'Lexend', category: 'sans-serif' },
    { name: 'Public Sans', category: 'sans-serif' },
    { name: 'Work Sans', category: 'sans-serif' },
    { name: 'Archivo', category: 'sans-serif' },
    { name: 'DM Sans', category: 'sans-serif' },
    { name: 'Be Vietnam Pro', category: 'sans-serif' },
    { name: 'Urbanist', category: 'sans-serif' },
    { name: 'Jost', category: 'sans-serif' },
    { name: 'Host Grotesk', category: 'sans-serif' },
    { name: 'Hanken Grotesk', category: 'sans-serif' },
    { name: 'Instrument Sans', category: 'sans-serif' },
    { name: 'Geist', category: 'sans-serif' },
] as const;
